BEGIN
   EXECUTE IMMEDIATE 'DROP USER CLINIC_ADMIN CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;  
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP USER DOCTOR CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP USER PATIENT CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP USER RECEPTIONIST CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP USER BILLING_MANAGER CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP USER PHARMACY_TECHNICIAN CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE USER CLINIC_ADMIN IDENTIFIED BY NeuBoston20241#;
CREATE USER DOCTOR IDENTIFIED BY NeuBoston20242#;
CREATE USER PATIENT IDENTIFIED BY NeuBoston20243#;
CREATE USER RECEPTIONIST IDENTIFIED BY NeuBoston20244#;
CREATE USER BILLING_MANAGER IDENTIFIED BY NeuBoston20245#;
CREATE USER PHARMACY_TECHNICIAN IDENTIFIED BY NeuBoston20246#;

GRANT CREATE TABLE TO CLINIC_ADMIN;
GRANT CREATE VIEW TO CLINIC_ADMIN;
GRANT CREATE PROCEDURE TO CLINIC_ADMIN;
GRANT CREATE USER TO CLINIC_ADMIN;
GRANT CREATE SESSION TO CLINIC_ADMIN;
GRANT CREATE SESSION TO DOCTOR;
GRANT CREATE SESSION TO PATIENT;
GRANT CREATE SESSION TO RECEPTIONIST;
GRANT CREATE SESSION TO BILLING_MANAGER;
GRANT CREATE SESSION TO PHARMACY_TECHNICIAN;
ALTER USER CLINIC_ADMIN QUOTA UNLIMITED ON DATA;