-- CLINIC_ADMIN USER
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.APPOINTMENT" TO CLINIC_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.BILLING" TO CLINIC_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.DOCTOR" TO CLINIC_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.MEDICATION" TO CLINIC_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.PATIENT" TO CLINIC_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.PHARMACY" TO CLINIC_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.PRESCRIPTION" TO CLINIC_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.PRESCRIPTION_ORDER" TO CLINIC_ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON "PCM.MEDICATION" TO CLINIC_ADMIN;



-- DOCTOR

GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.PRESCRIPTION" TO DOCTOR;
GRANT SELECT ON "PCM.PATIENT" TO DOCTOR;
GRANT SELECT ON "PCM.BILLING" TO DOCTOR;
GRANT SELECT, UPDATE ON "PCM.APPOINTMENT" TO DOCTOR;



-- PATIENT
GRANT SELECT, UPDATE ON "PCM.PATIENT" TO PATIENT;
GRANT SELECT, UPDATE ON "PCM.APPOINTMENT" TO PATIENT;
GRANT SELECT, UPDATE ON "PCM.BILLING" TO PATIENT;
GRANT SELECT ON "PCM.PRESCRIPTION" TO PATIENT;


-- RECEPTIONIST
GRANT SELECT, INSERT, UPDATE ON "PCM.PATIENT" TO RECEPTIONIST;
GRANT SELECT, INSERT, UPDATE ON "PCM.APPOINTMENT" TO RECEPTIONIST;
GRANT SELECT ON "PCM.BILLING" TO RECEPTIONIST;








-- BILLING MANAGER 
GRANT SELECT, INSERT, UPDATE, DELETE ON "PCM.BILLING" TO BILLING_MANAGER;
GRANT SELECT ON "PCM.PATIENT" TO BILLING_MANAGER;
GRANT SELECT ON "PCM.PRESCRIPTION_ORDER" TO BILLING_MANAGER;



-- PHARMACY TECHNICIAN

GRANT SELECT ON "PCM.PRESCRIPTION" TO PHARMACY_TECHNICIAN;
GRANT SELECT, INSERT ON "PCM.PRESCRIPTION_ORDER" TO PHARMACY_TECHNICIAN;
GRANT SELECT ON "PCM.PATIENT" TO PHARMACY_TECHNICIAN;
GRANT SELECT, UPDATE, INSERT ON "PCM.MEDICATION" TO PHARMACY_TECHNICIAN;